databases:
  - name: haniya

    databaseName: haniya_hrw8
    user: haniya_hrw8_user

services:
  - type: web
    name: budget-app

    databaseName: haniya
    user: haniya_user

services:
  - type: web
    name: hadiya3

    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:

          name: haniya_hrw8

         

          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false